# Site settings
title: Mixplanner
email: sales@getmixplanner.com
description: > # this means to ignore newlines until "baseurl:"
  Mixplanner is an innovative app for DJs, podcasters, radio presenters and
  promoters that helps you take your mixes to the next level. Whether you’re
  headlining a festival or perfecting your technique at home, Mixplanner has
  features you need to make an impact.
#baseurl: "/mxpl/" # the subpath of your site, e.g. /blog/
baseurl: "/"
url: "http://getmixplanner.com" # the base hostname & protocol for your site
#url: "http://richarddingwall.name" # the base hostname & protocol for your site
twitter_username: mixplanner
github_username:  rdingwall

# Build settings
markdown: kramdown
lessc: lessc
include: ['_pages']